rnaaliduplex = '/data/home/childs/bin/RNAaliduplex'
rnaalifold = '/data/home/childs/bin/RNAalifold'
rnacofold = '/data/home/childs/bin/RNAcofold'
rnadistance = '/data/home/childs/bin/RNAdistance'
rnaduplex = '/data/home/childs/bin/RNAduplex'
rnaeval = '/data/home/childs/bin/RNAeval'
rnafold = '/data/home/childs/bin/RNAfold'
rnaheat = '/data/home/childs/bin/RNAheat'
rnainverse = '/data/home/childs/bin/RNAinverse'
rnalfold = '/data/home/childs/bin/RNALfold'
rnapaln = '/data/home/childs/bin/RNApaln'
rnapdist = '/data/home/childs/bin/RNApdist'
rnaplfold = '/data/home/childs/bin/RNAplfold'
rnaplot = '/data/home/childs/bin/RNAplot'
rnasubopt = '/data/home/childs/bin/RNAsubopt'
rnaup = '/data/home/childs/bin/RNAup'

